apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:uyREmzkhjCDRCfq0fekBs/JYb0wb2PiN,iv:1xqDNQkWN3hWfnHRIsL/IXwrU4yWmAkWWu/KFUfltPY=,tag:C0wuJ370iK1i7E7oS/LvNQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:849S5CxpAT0TMM9Au8R45EIgMF8t2se+VTwlZ96UHj62hI2X2A==,iv:gy0bdX5e4DO1CR5D9uZkGERNup7oMpyDa0RCa5IlqVM=,tag:iRWGY7aUv3j+Ylot5eXU2w==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:gIeEZdkpeu0+RhJydVqOPg==,iv:ObE2XdlLi5GUA1EqOI5nleLfgEzAw778Bq8+xbakg/0=,tag:S9wr1JBTfhxCq3kFtspHpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e64k5fmzxstu4l5xea37ppx2ftzkw2hr6wvpjzhgfle2qtt6e47qef9ja5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpak1raitZSmQ3Qi9zbkRD
            d2d4SnpBVTdqaVJMaXlHNDFsTmh5TUthaWhnCjJ4Z0hZUGxJQWdsbHNlUVBpNFZN
            QjhCak9xKzJyOVJUd3lsL0pUZ25NT0kKLS0tIFVvRW83d0IzanVubVhsd0Z3SG1B
            WU4wZjBaRys0S1AyT2w1QVZHMUgzVjQKSiqiYV/sJwNhkSjiOpqnZVuIjUXw0Z5B
            OQJgrNZaKVJA/SoLUYQ1kBzEiuqVsx3BrWV7SKIWvs/kXKIIoUF/+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-26T19:38:59Z"
    mac: ENC[AES256_GCM,data:pDtq7MkuQNw7Kf4zCe45pMM7PvQyToZXvrpFj4xckJKXjHLJLL2pUvQUiXveNYt/hUwQco7MATK9GUiacNrwciljcGc2CZw9pw/q3rmccs62AxwLXPCddW9xlRbt1SgU3l7Rje1U7ISoiKxoat3EGFPb6cyaQREfhKXnDzgcuso=,iv:4L5QU8Mij5mpPH2PwwfXFrBlQByvYu3BxnCUDRrwNXI=,tag:tzYPS7EUfxowEDQEf27NpA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
