---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cilium
  namespace: flux-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/kube-system/cilium/app
  prune: false # never should be deleted
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  ## HERE's an Example of how to get Variable substitution right
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings 
      - kind: Secret
        name: cluster-secrets
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
