apiVersion: v1
kind: Secret
metadata:
  name: user
type: Opaque
data:
  password: cGFzcw==
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb
data:
  password: cGFzcw==
  root-password: cGFzcw==
--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb
data:
  UMASK: "0660"
  UMASK_DIR: "0750"
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  username: mariadb
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password
  passwordSecretKeyRef:
    name: mariadb
    key: password
  storage:
    volumeClaimTemplate:
      storageClassName: openebs-hostpath
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi


  image: mariadb:10.11.7
  imagePullPolicy: IfNotPresent

  port: 3306

  service:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/loadBalancerIPs: 172.18.0.20

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    max_allowed_packet=256M

  metrics:
    enabled: true
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: data-test
spec:
  # If you want the database to be created with a different name than the resource name
  # name: data-custom
  mariaDbRef:
    name: mariadb
  characterSet: utf8
  collate: utf8_general_ci
  requeueInterval: 30s
  retryInterval: 5s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: user
spec:
  # If you want the user to be created with a different name than the resource name
  # name: user-custom
  mariaDbRef:
    name: mariadb
  passwordSecretKeyRef:
    name: user
    key: password
  # This field is immutable and defaults to 10
  maxUserConnections: 20
  host: "%"
  requeueInterval: 30s
  retryInterval: 5s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: grant
spec:
  mariaDbRef:
    name: mariadb
  privileges: 
    - "SELECT"
    - "INSERT"
    - "UPDATE"
    - "DELETE"
  database: "*"
  table: "*"
  username: user
  grantOption: true
  host: "%"
  requeueInterval: 30s
  retryInterval: 5s
