apiVersion: v1
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:GHTj10CuJEf4NG6OurBvs78pzh/Af0KAiJJbmw==,iv:U89ATj/afYVKR273mtO+gLc7W6pWb0+JRzqqQTgYVmg=,tag:RVaS72kV2ez9MpC4wBEa5A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:OI2dYYkNw/VDflS+cXPDBmKFD+nMw8/1Q2W+08QWmYeq/dqi7OAlH3VZzTUalJUKCMioGw7RA8M=,iv:sUMIFN13WHU5mzKXuSsLSsGvG2dHTDgT/D3TvxGo4QQ=,tag:PPHaLiw/Du3sPGAQ0Mkvjw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: snagger-secrets
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jp3qvp8yapslrcz22xzepwwt0nhcjp6tdjwe33dqtl5uvqy2fe0s0tus24
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArOW00QjNiVkV2NEdZa2d3
            bmNqaWMzNThsaDZTdFdaMlZsQmNPMkpqVkZJCmZ2bVpaUXNycEFJcDNEMDIxSXV1
            VURFb0RGS2hVVTlzb2J4WU1wSnNMMm8KLS0tIEg3aWx6ckN4MGlOd3JLa0dBSkxk
            Vml2SXZCMDVydFFMQXpjWjc5bzVDRG8Kn2xmoY2B0lQZionMWFzUnii78lj5OdRL
            H1+09ZBvvEP0AzRUFJwa/sw8BLD9yNruS5l7Y8i2G/Lp6NE+fAzIlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-20T22:57:48Z"
    mac: ENC[AES256_GCM,data:t0XM9WACU4st471VSrRAkI0Vseh/US0svJlJMkiD/+ES0x8FzyRA3juZm/XelGYhii1H613E098x3Juh01dP64TjJYpqHJTC1Qg3I2jR1wA/1l1K5qBkmyrO3nTQEItCeLGKdEGZNu95l7w1q8VDlzhepKiq/dBYMHXsJmFJTwA=,iv:7bMSZi/TPgjxrhOtY5Bv8YL0+RCIwhZ3jWifrmtuE7o=,tag:mYq+/+WD3ot2XuTWQoaP6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
