---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dbtest
  namespace: flux-system
spec:
  path: ./kubernetes/apps/default/dbtest/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 5m
  timeout: 10m
