apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:0Zww3+ssiyWAGKmTywYUTnqX+cRin0ZlHT9zzSQxDdtF67jsFpw/eQ==,iv:DWbDuEJWc2Tu/b+4qh6CrPGS/chhqgp3xle5Aq6nc/o=,tag:BcC1f17eZIAbbKsk2U2aNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e64k5fmzxstu4l5xea37ppx2ftzkw2hr6wvpjzhgfle2qtt6e47qef9ja5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dE9IY2xjT2JFOEJBWjZN
            cC9KTEcrTEdxV1UwSjNneXB4eDRsd2tTUUZJCjRCV3c1N1NkOFhGY1lrem11SzdO
            eTc5NkF3Q2NVVEVIWlJpRExpUUlWczQKLS0tIDhUYWRxVUhzUTNxdndjV1dvMHc2
            WllFVnNMMjBWYzkxdEVOMHpDSkpZQ1EK7oYeItLd4Er5W79JS8IEtTMirGeRiXco
            gv7/WkYdjkgH65uKgsHlI4GdT/yGorQfFE8ix/llYGGIP3qoLVamfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-26T19:38:59Z"
    mac: ENC[AES256_GCM,data:L7U7Q7gzItDmv2TWkfsC1A8UChhA8b9/t7y4jDCIfPvHQkMHwV5MwDE5MNKeQbw6kTyu/WVP7FI/onYb4P/eHncUTShsbGqy2TLsz70AyRaPZLxcjBTntxRs/RAnOpf4kUIe6neYzJPTlpQQ805qEZ1agSyk5IKCjLB88XeGRzk=,iv:EHnb6q54yEfKqssOXQa40Y03RnwiTXUTGDKuOO+MKxY=,tag:DTrfI//FU5Zf/O9V+QhVGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
