---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app obsidian
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      obsidian:
        containers:
          app:
            image:
              repository: linuxserver/obsidian
              tag: 1.9.10
            env:
              CUSTOM_PORT: &port 3000
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      app:
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: note
          hajimari.io/appName: "Obsidian"
          hajimari.io/group: Productivity
          hajimari.io/targetBlank: "true"
          hajimari.io/info: "Tool for taking notes"
        enabled: true
        className: internal
        hosts:
          - host: &host "{{ .Release.Name }}.koopmans.co"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts: [*host]
    persistence:
      config:
        enabled: true
        existingClaim: obsidian-config
        advancedMounts:
          obsidian:
            app:
              - path: /config
