# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: minio
    namespace: default
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:EXEbKbteQA==,iv:dmq7R8XUCebhG1vhAaqrJ9Ymh/78EsQhoAPT9W4QhnE=,tag:6O2WFLd0IRDOHBha+sC5Lg==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:UvEOgO8qvwpRekDkpyXBs7sOIDuCdiT90w==,iv:NpQQSMaPnWRJi+W+vu6KHohge+Kx7ZhHy02S+4GEUzI=,tag:cmro8jxpRQVeOPI9gN+4rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jp3qvp8yapslrcz22xzepwwt0nhcjp6tdjwe33dqtl5uvqy2fe0s0tus24
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQanNtUXgyeERxaGRYRVpp
            cUpoejYvVjIrUWJmMW10NFZUM05UbnA0UGt3CkRhQlVXSnZ6c25NZzhXd3lBL0t0
            NDJUZVlGQlVtaFZLby9HbEt5WDF4MkkKLS0tIGJJdUdwK0RXbDBGTlpFdlhaMEVt
            TVBCL25aK2QxUnpETW5CNDVmb3ZONUkKD0AXS2ZtSEPqF+LvP/tN61a4cLur5ay9
            LuFE2b2X7icO3Y22F1YkXoOOUcw9uGevujOGfeQUVMUu/xdkWh67AQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-11T00:44:03Z"
    mac: ENC[AES256_GCM,data:pTApLoAbAAxdnFKFkvMmLoejkCI9yva/JvOLm1Jwe7alLvbuv+e4jNljUy/bXLFbaLe1o1xgsLFSIeYyNiELYBlmh8LoXSSSVydPDmhDsk79idK9M9xaqhfUDf3/mGQs7NZErJ+PS0My5bqS3himIAB7JoL9TRYcRA3XAZBByvg=,iv:FbHfnnVSNyf7zVdVxJLSY4TSmp+p+r/pqymmR4/aP8c=,tag:NBE8YaJp3p5t5i67JeunqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
