---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: smb
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        strategy: Recreate
        containers:
          main:
            image:
              # https://hub.docker.com/r/dperson/samba
              repository: docker.io/dperson/samba
              tag: latest
            env:
              TZ: "${TIMEZONE}"
              # PERMISSIONS: true
              SHARE: public;/srv;yes;no;yes;all
            service:
              main:
                type: LoadBalancer
              annotations:
                kube-vip/loadbalancerHostname: smb
                loadBalancerIP: 0.0.0.0
                ports:
                  http:
                    enabled: true
                    port: 139
                  smb:
                    enabled: true
                    port: 445
            persistence:
              data:
                accessMode: ReadWriteMany
                enabled: true
                mountPath: /srv
                size: 1Gi
          
          browser:
            image:
              repository: docker.io/filebrowser/filebrowser
              tag: latest
            service:
              main: 
                ports:
                  http:
                    enabled: true
                    port: 80
            ingress:
              main:
                enabled: false
                className: external
                annotations:
                  external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
                hosts:
                  - host: &host "{{ .Release.Name }}-external.${SECRET_DOMAIN}"
                    paths:
                      - path: /
                        service:
                          name: main
                          port: http
                tls:
                  - hosts:
                      - *host
              internal:
                enabled: true
                className: internal
                hosts:
                  - host: &host "scans.${SECRET_DOMAIN}"
                    paths:
                      - path: /
                        service:
                          name: main
                          port: http
                tls:
                  - hosts:
                      - *host


