apiVersion: v1
kind: ConfigMap
metadata:
  name: directus-mariadb
data:
  UMASK: "0660"
  UMASK_DIR: "0750"
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: directus-mariadb
spec:
  rootPasswordSecretKeyRef:
    name: directus-mariadb
    key: DB_PASSWORD
  database: directus

  image: mariadb:11.7.2
  imagePullPolicy: IfNotPresent

  port: 3306

  storage:
    size: 1Gi
    storageClassName: nfs-provision

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    max_allowed_packet=256M

  metrics:
    enabled: true
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: directus
spec:
  # If you want the user to be created with a different name than the resource name
  name: directus
  mariaDbRef:
    name: directus-mariadb
  passwordSecretKeyRef:
    name: directus-mariadb
    key: DB_PASSWORD
  # This field defaults to 10
  maxUserConnections: 20
  host: "%"
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: grant
spec:
  mariaDbRef:
    name: directus-mariadb
  privileges:
    - "ALL"
    #- "CREATE"
    #- "DROP"
    #- "ALTER"
    #- "SELECT"
    #- "INSERT"
    #- "UPDATE"
    #- "DELETE"
    # - "ALL PRIVILEGES"
  database: "*"
  table: "*"
  username: directus
  grantOption: true
  host: "%"
  # Delete the resource in the database whenever the CR gets deleted.
  # Alternatively, you can specify Skip in order to omit deletion.
  requeueInterval: 30s
  retryInterval: 5s

