---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: qbittorrent
  namespace: flux-system
spec:
  path: ./kubernetes/apps/default/qbittorrent/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
  interval: 30m
  retryInterval: 1m
  timeout: 3m


  ## Don't forget to add this to the namespace level ks file to combine together.
