apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:UMHg1dxMgNqGwEZM1yDK41Rn1X+uFVzjtwgE0BKRQLXSIZcXdg==,iv:QR6fj7TyXe0rFI+pV17GFgCqcymYbxSBMBKa5zGRGb8=,tag:cThXMf+rs8PsPxnIh28Y7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e64k5fmzxstu4l5xea37ppx2ftzkw2hr6wvpjzhgfle2qtt6e47qef9ja5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZmk0aXNxUjZORlNtd0ZW
            Y3c0OExCdzhyN2NPWlNYMDB2SmRJVUhjWm5NClVnbC9FM2MwZzIyOXptME8xTldW
            UU9remlHK1JnN0dtOFh1S1Vud2tIVE0KLS0tICtOTkUzbGN0ZVg4WlBxeUcwcklK
            NVhTYWRMODRCZXNGcU1IQzlFK0VkNU0KWYuSjThuyY+UCesa+7BVNYjGIbNNg9NE
            k2QePpSHuA0TVPcygBHg+VXslGKqYqd9MlwZ6NfJ0vAq/vscbaS/ZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-26T19:38:59Z"
    mac: ENC[AES256_GCM,data:b2cTzHSYIhwletkiY9zWTIlm3z9BDKP96j7a4anxLYWh1e/2h28qLgBiwH5FDqy7xUIvwF2C5HuXuw1V6ZDnnyCeRPCuT6r5z8+0uIeZKl4Bq5/rOXDQL2RYhtSunq0mc1aKX00wl5NoILyPZiGnaDCGrvHVIJX4cqQxQg4/zow=,iv:9nSl7fy4zdIxu23FzVQGzDRem/FKgOjVQQtVXTOPPRg=,tag:D9Oi1+0ebXqJTUdAyaKKTQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
