apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:hrRBoTEee5cct/QA6jzZ4gGs0nvsHz6S,iv:YLK8EA1IxtpmPp8JaVvS0oOY3lKSJalnLm2cOSphqdE=,tag:GT4zlmJ5IjxgyMRJpyT+WQ==,type:str]
    api-key: ENC[AES256_GCM,data:2JBHI7BmkxbMDUnGdQ8OKgPNZMkgZGiWwCFdvOeAHeRA8YEeDQ==,iv:9i7onQ69AGdZocjhRqUfNdIcsJYKdv8Ftu7+nPRvNW4=,tag:tagHJHboG+7Ffu4PpQYmfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e64k5fmzxstu4l5xea37ppx2ftzkw2hr6wvpjzhgfle2qtt6e47qef9ja5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4em1KaklnZEJ2RU1DYWV4
            MDNpK1BlbnZSWDE0NG81SHVJQUVjYVdzYW5zCnpzYWJvajJNdEJRd0R3Y1BIOUZB
            Wml3clRNL0JrOUcxVHlqbFlsRjEzQ2MKLS0tIHlqUmpwTjFNSGhmS3R3ZlZPVm5F
            V3ZDMGRjTmlsSHRQYTBTZ3BxOC9HZVEKfE89eMCl1GexIzIkptJ/KUal/M2Gu2c9
            pa2Zk36MOqJLhqtIzFD4m4IuzYGoBTsdIzxf++rjqPTH7imRlDjVDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-26T19:38:59Z"
    mac: ENC[AES256_GCM,data:0CZF8rCRfNAW2oRGm3YDGOK+HVa32SPuFMJQZUuMUyRPaErG9ZmmynJ/sEt0E381Zi7iTA5iuoiEW8zXmHxKNXdT0GRn0pbTDHmDv6Vf5qRhIrghv6njO2IHECHjP4aQuKJve4ibkGFHT9alqEbqCNMw6BUiZ3cIDgHJ3DmDmck=,iv:gK3V4Q/IUNURa0b72cXpQgX2azQ3SuudLPs2tpEnV9w=,tag:/o7UhX4GRrYK0ia/ICyAfw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
