apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:Bhgwt6y0orvitCcbWVkfqPz7u2AIz/y7iySq8LAHR4umg5bDiL8dlvo/zDJuSou8nbwE8Vk5WLOatuer,iv:+TzTvcx3LkohufPqsuNlhG2LHevzrn05yN8PqG+IEkc=,tag:YcjRSjji1tJ49SwXac6orQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e64k5fmzxstu4l5xea37ppx2ftzkw2hr6wvpjzhgfle2qtt6e47qef9ja5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Q0hhTU9RTGZPZDBiS21n
            SU1vdjdLS21kNnBoSE9DUXplM2hYT3FUZlhjCnYyMDN0ZWFUbUhQcnVjMlluQ0tt
            YlUrSkpoK3FBUWI1aTB0SHY4SzFIaHMKLS0tIEJ5eldqNmV1THF6NTJqWTlmRXJZ
            OGdhWU5xdFhhYzkxdDk2bkI5eVEwSlUKjCM1X2FieTsJcwxNfvmfu4u6fDlu9gjG
            L4+vnvUgE/De/OogULUYX8lGunzjP2VmRFuZg731UvCCrlN30b7WKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-26T19:38:59Z"
    mac: ENC[AES256_GCM,data:+MySe44R+UWHn/9WmNGrDzXc7DSGHzp7k8ZEOyPtCSfMBJigjWFyKZLf3h/rxQFRSVfiYmePtAVCfx4xIjnlCvwH7dpquJ9eo96cYLGpCUxn5zt7Boc7YMIQ9LQLSd2t0U2yzGJ0ed1TS3trgeJpSy70+OKW/3ESzPS7DI8/84k=,iv:vv/86iJbV4fqlkvXOipXa7y3rqQZm4skCyW7y4hsmgE=,tag:S/epVqRtVmk5pg38OGbQLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
