apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ZJQu9zeFsEbiWBg=,iv:pJjgL4T0COmu4wZUxrYWlUklS4zDPtHhlJkRVzNGAPI=,tag:f2oK+FsSyi6J59PkcpqzTg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:7oABfOlcApt2w3oUt3XXL+It8To1TfUC,iv:Iy5T454SHEYattVZ91uDb5V2lS6VkrW9Lrw086qXLDQ=,tag:2ggHHrh8J/RxDfwRqTY3mA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e64k5fmzxstu4l5xea37ppx2ftzkw2hr6wvpjzhgfle2qtt6e47qef9ja5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRXIyNjZjODJ0SzB0dlhp
            MVQwd3p5OGpMWUp5dTQwVFZXeFJuYjVob0JNClVCTXVTdWVlc0RydDVUczdSQlMx
            L1dkWGhKOGFYT2Y3QlVheHJjMFJJNVUKLS0tIGdrWEFJUk44RjhEdVdQcDFMN2tQ
            czB4UjBxanVqWkRWN2JOeWJQTkRmVmsKLpALsPc7ZsNoQ1EfpGytQLKOUt5y4kil
            bF7S7iGuVZdTdSBQ2Xgov9KUJHNKKvfTCVap4oG5ULVbPwNWn7Jqmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-26T19:38:59Z"
    mac: ENC[AES256_GCM,data:RNzlZN1KfRG5VVfiAisunCaS6KUaCf09zve7oTgamI0Az8wQNcn2YXC3BBD0kwezoAJ1Np89EIcOjOFtJvg7uAOZzySI6gseiOnaDUi8fvxotYOw7Ks6Vm8P7hDfBRgIUMjiHoF/qBXij+3MNzaUI2eKmOtHHPEAGH6Qm2dbPd8=,iv:QA1uNWsPXabn+qqQdpsPWEAIhu7XVMQLMN3z/+8i2Fs=,tag:Dv80MJvLHH7NyN1P3oaCfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
