apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:WgYGF5xGSDKmDlvYL5mQVJ1fa1kJosLE3Sef8zGWexRGVR24Y+a4JqzC20Htm1okjCxbdRLQ9Ak4QzrnsK9aKGJPX8dWGisHi3OA/uwWVOpibqn+8hNbBvenxKINBA==,iv:Ntto4OBCN3Wdo+oaR1GH5IwbOBrBGl3VSBBU0RYtXH4=,tag:Y0w0jtGKVnbeEU1GBwXvlg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:UBSm8JcSURfkycQ=,iv:CTfVKbissphp79sc05XO3h669tWGvKJlCkNgQTs/JvY=,tag:tbKbcKEM6zj6u4l4uyyO9g==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:j60HF/6Y8Xm6ajh2gMgF8oIEz21wiwPw,iv:k6tF7K7jk27tWuEWcv5zGRhs7rzSKVVduvUwDjNEMVw=,tag:lGFZquyi1eVTQ4jumR2Q1w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:0mPjunGwR++UNJmlBED3C/bsVb06VRbOtKh6xv3JQfz/csg7,iv:71JRGt5eiLsZcH0erdtJ3hCO/NRkzORl+hgFTUPk1Zw=,tag:DsljKTxpz57Pprj1MgcvMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jp3qvp8yapslrcz22xzepwwt0nhcjp6tdjwe33dqtl5uvqy2fe0s0tus24
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBheCs0Qkt4MnBIOEx0OGUr
            VENlWkVGd3NCT1oxMjFXOTk1NG5TSVZqUkZVCkVYUFFqcmp5Nk9zVlNiOENDNDRp
            Wlh4WExYRTNtaXpjaFltVXVOZm9CcUUKLS0tIFN2eTA3L0ViOHordDloSkI3anJu
            bmxOYTBQYURiSEQvb2xyUVNnM3lSYXMKAiuKyL73NJp+xtGT+mMtlv8r3+jiCq+J
            lI8S+jUFlHS3mplCiVbVq5PfsylCxaNsPeSvFCE6MWGrc4QM7e/h9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-05T04:41:38Z"
    mac: ENC[AES256_GCM,data:nN3qCHmFBlDKa+ueAHVayeUMoMmYyS/ObtvhXowQt2uT/hVMrXw4ICjLxQjRPUsx/WVnZzP0Bwqrp8Vx0OIUrFYi2J0XtupZR6dEWnHXDkBk/FQLWpReh4olGF3X6GOAoVD1EHaX4qhOFBBSYRBPcQP2e5VbPKB/NAqQQA/pK7Y=,iv:B4+uC0zUqZWXGEWMpK3bzcgk5zNlsVGPZj9eQGRjfNU=,tag:0mFKij7VuhZXW95bqCx87Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
