apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:KDoUZH8d2fjuR2RMZLkg/td351Y0R5Rh573kVN+T90juhHv80uYTgoNa1vMgw0SCtCQpn2Ipcy/Gt8fioqUZFgnC2vPEsl/v1Rbk1q1AcIpSw6ZFp5mIAaUONUaDog==,iv:kgE/RXqc+5kjMWkddW8i8AI5ub63QYz0KjPa8tIv4to=,tag:tgdnc+yIzxWAdpiJ5W9CUw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:HOBerddZ5ZorzAE=,iv:K8PhSOEbj0tmeWBk373uWoPhUeIbbD3ZAPeo/OYEMXE=,tag:I8WMDyblVIHQj13FEa0IDA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:k7es0jOMnovRYrNFE/BC8HsbQPDNLc4m,iv:LAq5BK9DHkeLZr40hHpvW5Tqhh1ktjSUPSsDP0cieeA=,tag:6KA+OlOSyRGUWdda/AbR+w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:htCKjjy7Yv835jamego66BgvMfshv2IYP2LokksifXe3eZid,iv:+r3Yg35OROGouM5f1kkG/ZLKvPJydKEZG3YiKGzZGvE=,tag:C0GqKJEh2Z5lzV+bL7NVzQ==,type:str]
    S3_BACKUP_ENDPOINT: ENC[AES256_GCM,data:2jmwfGS6Vw72ljKtB8WaKhCSQ46NaKslAjM53tqOsPRGDgMrOHz0sjahW65fA+U6nCWsCw==,iv:FlOw/2+8zEOdZSFWu9iJXGF9iA8lNlMDa9LdIJgBA9U=,tag:PtV6A90oHvzA4414FmBGYQ==,type:str]
    S3_BACKUP_BUCKET: ENC[AES256_GCM,data:l1+VDYEVe1P9pP98XkXq,iv:IkuVGnwmPEYwemeYMCMv475e8SIx+l/tH3IblamQfEk=,tag:/TmbOZUzUFNgNlf5USwkpw==,type:str]
    S3_BACKUP_BASEPATH: ENC[AES256_GCM,data:jeJmPbWP13Q=,iv:Z6xMN3ZQQ3ZXPChqJJGOEn33BKs5isBl/kl6usSgEoo=,tag:wMK8nZfVC8oY+O6pZgMXgg==,type:str]
    S3_BACKUP_REGION: ENC[AES256_GCM,data:X+FeNSabyz3W,iv:2xv/bHAFOc2nD/iurDWBlTgVZq99KiyLhXJKrJLpvgE=,tag:V/YcDFBNl3UrDljEApeQpw==,type:str]
    S3_BACKUP_ACCESS_KEY_ID: ENC[AES256_GCM,data:voSEgZD8S5II74uWNGS8WgMZRyQ=,iv:X+38wEkpIiHqKjkt3HOwykReRiHGOf0tLW1n2k8YpyA=,tag:0pEI1PtyWbJaSjUk86xd5w==,type:str]
    S3_BACKUP_SECRET_KEY: ENC[AES256_GCM,data:VvxtSxeDpMZFl5hVqYCLUCIKaI7Keyc8V1c43OjHv9s9GYUacYCIXA==,iv:k0BZ0yccpR2sLB8yoWBqzwU1K5yaRFaKDVfZ2BMFhug=,tag:tSeU2Sb0yyKkQav35vHQMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jp3qvp8yapslrcz22xzepwwt0nhcjp6tdjwe33dqtl5uvqy2fe0s0tus24
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTkkzbWJFcDhUQlprRldI
            QyszL0laNW1Vb1hzRXZjQy81SmdpS2dLRVNBClNLdjdBSUQzMUYyRFg0NVBDTXFi
            ODUwTUZKaDJ5WnRGRUpZeHVJNUJRRmMKLS0tIDRWYThjZWFscmwxN0VHYVpPUmtz
            UE9sby8vYUpoeDNDZEFTdElaN0lGbFEK8pECBAFx7U1KuMvYdlV+vnK+xuUOxZI2
            759S5OteKKCLPOoLiTJrTv6N+8CEi68wIEG/2JN8Z2bQPINo/AQUew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-31T01:11:25Z"
    mac: ENC[AES256_GCM,data:R8I9VDA3F+VwpH/rGrYAf3bApkYqt5/Qe/UR3TYncF5vGBKdYVDEp5JQOhiHvj4167jEMSFmmNfz5C/izR4F0BZImkgc+/elKA6ltIyEzJuJCaQen/lRkSkWl9z6CwHMmnODWHHb/a+1Eisyx+wMpV+1/cxykHwCLyX8Saljy2c=,iv:Sxd1V7m6HOgxQCCJz0ZI85yZ8sv3aeCKHjLMOIlkjJw=,tag:aKlz6gM2BtlSC1nBH9K/EQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
