# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  uninstall:
    keepHistory: false
  values:
    controllers:
      plex:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: plexinc/pms-docker
              tag: 1.41.5.9522-a96edc606
            env:
              TZ: ${TZ}
              PLEX_ADVERTISE_URL: https://plex.${SECRET_DOMAIN}:443,http://plex-direct.${SECRET_DOMAIN}:32400
              ALLOWED_NETWORKS: 192.168.1.0/24
              PLEX_UID: 1000
              PLEX_GID: 1000
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /identity
                    port: 32400
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 6Gi
    service:
      app:
        controller: plex
        ports:
          http:
            port: 32400
    ingress:
      app:
        enabled: true
        className: internal
        hosts:
          - host: &host "plex.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        type: emptyDir
        globalMounts:
          - path: /config/Library/Application Support/Plex Media Server/

      # Separate PVC for cache to avoid backing up cache files
      plex-cache:
        type: emptyDir
        globalMounts:
          - path: /config/Library/Application Support/Plex Media Server/Cache

      tmp:
        type: emptyDir
        globalMounts:
        - path: /tmp
      transcode:
        type: emptyDir
        globalMounts:
          - path: /transcode
      var:
        type: emptyDir
        globalMounts:
          - path: /var/run
