apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app nodered
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: docker.io/nodered/node-red-docker
      tag: 3.1.5-18
    env:
      TZ: "${TZ}"
    service:
      main:
        ports:
          http:
            port: 1880
    ingress:
      main:
        annotations:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: &host "nodered.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      config:
        enabled: true
        existingClaim: nodered-config
        mountPath: "/data"
    resources:
      requests:
        memory: 64M
      limits:
        memory: 1Gi