apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app nodered
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: nodered/node-red
              tag: 3.1.5
            env:
              TZ: "${TZ}"
    service:
      main:
        ports:
          http:
            port: &port 1880
    ingress:
      main:
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: transit-connection-variant
          hajimari.io/appName: NodeRed
          hajimari.io/group: Automation
          hajimari.io/targetBlank: "true"
          hajimari.io/info: "A neat low code platform for IoT and automation."
        enabled: true
        ingressClassName: internal
        hosts:
          - host: &host "nodered.koopmans.co"
            paths:
              - path: /
                service: 
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    pod:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        runAsNonRoot: true
    persistence:
      config:
        enabled: true
        existingClaim: nodered-config
        mountPath: "/data"
    resources:
      requests:
        memory: 64M
      limits:
        memory: 1Gi