---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mariadb-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: mariadb-operator
      version: 0.27.0
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: flux-system
      interval: 5m
    