---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tika
  namespace: flux-system
spec:
  path: ./kubernetes/apps/default/tika/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m

  ## Don't forget to add this to the namespace level ks file to combine together.
