apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:n6Kgjng2wNwQMiaMXul4YrIq7/d+r6Mm4Qyne10E1Ns=,iv:CkQSnxtnsb0neocEfwKqLIMKgy8CfNPMQTT8cYy7qXM=,tag:FhyMgYghsBGXzxQTd+8AfA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1jp3qvp8yapslrcz22xzepwwt0nhcjp6tdjwe33dqtl5uvqy2fe0s0tus24
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UWxEK0JYeFF6TlpmVzhE
            MkFhTlczM0x6eXV4Q2tPWm5vazBCTmFFaTBJCitPSytFb09oNUpJSnF4TTY5Sklr
            c2xwVWFaazJUYm5URVhQalJjT3FXUFUKLS0tIHprd0xWQ3RacGhhY0VsUHU2WkVi
            aytHSWVCNzl6dXNWTUkwOTFxbmFRNVkKobiYZWa1kmsXzhZwHIdgwTBj+1Tu+QPN
            mua4l0EOS3IPn/WFVeFP049KfIOjPLY+zDvhKTTRn20R1etO8p/++Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-05T05:46:08Z"
    mac: ENC[AES256_GCM,data:tNk2RKYO8Su61xbi5yKvXll/SA9sB0Z5UtbAZVe5PekHFyuk96dARkozLOxrmXhms6/2WAkuQ1nepYu3P+fdIxpf166XVCNnsBcAWWCqrDosJbRdvxCC8c1aBHEKhLMC0ckkapOd6DCXuNBH5xRClKEXkAFvWSd2UY1SFgIluyc=,iv:uUdlz00ohdkOwcBdwGXQwXLB0xHJ5Lz8BtgFXSbUMK4=,tag:J4IJ9tFzMC9BkTansgLduA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
