---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nodered
  namespace: flux-system
spec:
  path: ./kubernetes/apps/default/nodered/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta2
      kind: HelmRelease
      name: nodered
      namespace: default
  interval: 30m
  retryInterval: 1m
  timeout: 3m
