---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: default
spec:
  storageClassName: nfs-provision
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-nfs-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine-nfs
  template:
    metadata:
      labels:
        app: alpine-nfs
    spec:
      containers:
      - name: alpine-container
        image: alpine:latest
        command: ["/bin/sh", "-c", "while true; do echo $(date) > /mnt/nfs/test.txt; sleep 30; done"]
        volumeMounts:
        - mountPath: /mnt/nfs
          name: nfs-volume
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: nfs-pvc
