name: Lychee

on:
  schedule:
    - cron: '0 0 * * 2'  # Runs every Tuesday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Lychee
        uses: lycheeverse/lychee-action@v1
