name: Lychee

on:
  schedule:
    - cron: '0 0 * * 6'  # Runs every Saturday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Run Lychee
        uses: lycheeverse/lychee-action@v1